


spring:
  application:
    name: ecom-store

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-database
    username: postgres
    password: 1234
    hikari:
      pool-name: Hikari
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        generate_statistics: false
        order_updates: true
        order_inserts: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false

  liquibase:
    change-log: db/changelog/master.xml
    contexts: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://moldavets.kinde.com
          jwk-set-uri: https://moldavets.kinde.com/.well-known/jwks
          audiences: http://localhost:8080/api

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080
application:
  client-base-url: http://localhost:4200
  cors:
    allowed-origins: http://localhost:8080
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300

  kinde:
    api: https://moldavets.kinde.com
    client-id: ${KINDE_CLIENT_ID}
    client-secret: ${KINDE_CLIENT_SECRET}
    audience: https://moldavets.kinde.com/api

  stripe:
    api-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}



logging:
  level:
    org.springframework.security: DEBUG

